version: '2'
services:
    projectjhipster-app:
        image: projectjhipster
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://projectjhipster-postgresql:5432/ProjectJHipster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    projectjhipster-postgresql:
        extends:
            file: postgresql.yml
            service: projectjhipster-postgresql
